export enum MutationTypes {
  CREATE_WORKSPACE = 'CREATE_WORKSPACE',
  CREATE_OVERVIEW = 'CREATE_OVERVIEW',
  COPY_WORKSPACE = 'COPY_WORKSPACE',
  DELETE_WORKSPACE = 'DELETE_WORKSPACE',
  SELECT_WORKSPACE = 'SELECT_WORKSPACE',
  ADD_FILES = 'ADD_FILES',
  SORT_WORKSPACES = 'SORT_WORKSPACES',
  REMOVE_ENTRIES = 'REMOVE_ENTRIES',
  LOAD_INSIGHT_FILE = "LOAD_INSIGHT_FILE",
  SHOW_UI = "SHOW_UI"
}